### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by alroyt** [DoubangoTelecom/ultimateALPR-SDK#112]
Hello team. All operations in a new version of JETSON NANO, even if the ROOT user ends in Permission denied.
~/ultimateALPR-SDK-master/binaries/jetson_tftrt/aarch64$ Permission denied
./trt_optimizer: 1: ./trt_optimizer: ../../jetson/aarch64/trt_optimizer: Permission denied
-rwsrwsrwt 1 jetson jetson 34 Nov 18 13:52 trt_optimizer

**Comment by DoubangoTelecom** [comment]
[trt_optimizer](https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/binaries/jetson_tftrt/aarch64/trt_optimizer) in `jetson_tftrt` is a symlink to  `jetson/trt_optimizer`.  Looks like changing the rights on the symlink doesn't change it on the actual file.
Run `chmod +x binaries/jetson/trt_optimizer` before running `./prepare.sh`. Other files like `benchmark`, `recognizer`... are also symlinks .
I would recommend using `binaries/jetson` instead of  `binaries/jetson_tftrt` for your devs as explained at https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/Jetson.md#getting-started_jetson-versus-jetsontftrt_recommendations
