### ISSUE TITLE
Whats the performace and accuracy on moving vehicle ?

### ISSUE THREAD

**Issue by rsingh2083** [DoubangoTelecom/ultimateALPR-SDK#179]
Hi,

I want to install this on a jetson_nano or Xavier-NX etc and keep it on backside window of a moving car.
Do you have any idea about its performance and accuracy while running on a moving car ?

**Comment by DoubangoTelecom** [comment]
Hi, the fact that the camera is moving doesn't have effect on the accuracy as long as the images provided to the engine are clear. Check https://www.doubango.org/SDKs/anpr/docs/Rectification_layer.html . The ANPR engine accepts an image as input, doesn't matter how it's collected. We have commercial deployments where the camera is on a Police vehicle and it works fine. Please also note that the server version is more accurate than the mobile version when it comes to distorted plates (https://www.doubango.org/SDKs/anpr/docs/_images/rectification.jpg).  
These kind of questions are better handled via the discussion group (https://groups.google.com/g/doubango-ai) instead of opening a ticket on the issue tracker.

**Comment by rsingh2083** [comment]
Sure buddy,  Ive purchased the license. Please send the license key asap.
Id very very thankful

**Comment by DoubangoTelecom** [comment]
> Sure buddy, Ive purchased the license. Please send the license key asap.
> Id very very thankful

You should have received an email from the bot asking you for your company name and the target platform/OS. If not, check your spam box.

**Comment by DoubangoTelecom** [comment]
I have rebuilt the models for v3.3 (more accurate) -> https://www.doubango.org/SDKs/anpr/optimized.zip. Cleanup your [optimized](https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/assets/models.tensorrt/optimized) folder and use the files in the zip.
