### ISSUE TITLE
ANPR inference is slow 

### ISSUE THREAD

**Issue by AdityaZ12** [DoubangoTelecom/ultimateALPR-SDK#186]
Hi Sir,

Just one last issue which is about inference speed. 
On jetson nano (RAM=4GB, SWAP=8GB)  it takes almost 58 minutes to completely detect number plates for this 6.44 minute video file https://www.youtube.com/watch?v=xZMrRB36CVw&t=0s

Please let me know what can be the reason for this. The code I used is same as mentioned here https://github.com/DoubangoTelecom/ultimateALPR-SDK/issues/184#issuecomment-898861137

Even after overclocking Jetson Nano : CPU = 2000MHZ, GPU = 950MHZ, still only 15 minutes less in inference of 6 minutes video.
Sir please tell what can be the problem Sir.

**Comment by DoubangoTelecom** [comment]
6.44 minutes are spent decoding and reading the video file. The JSON result contains the duration it takes for each frame and if you check it you'll notice the inference is at realtime. The code in #184 isn't optimised, you should not use SWAP memory, OpenCV is very slow... To make it short, our SDK can run at realtime and you can verify it using the benchmark application ... but your app is slow because the functions you have added (read video file, MPEG4 decoding, OpenCV drawings...) made it slow. This is out of scoop.

**Comment by DoubangoTelecom** [comment]
For developers reading this ticket: the title is misleading, the inference isn't slow it's the code at #184 and has nothing to do with UltimateALPR. Even if they comment the process function the code will still be slow.
Additional note: As explained at https://www.doubango.org/SDKs/anpr/docs/Benchmark.html#nvidia-jetson-devices, parallel mode is 3 times faster and for no reason you have disabled it (see #184 `--parallel false`)
