### ISSUE TITLE
App Size Issue - Android

### ISSUE THREAD

**Issue by janaksuthar1st** [DoubangoTelecom/ultimateALPR-SDK#251]
It covers around 190 MB for Video Parallel example app,
Is there any way we can reduce the app size for mobile device only ?

Found that lot of models are there in assets cause size issue.

Any lead will appreciate

**Comment by DoubangoTelecom** [comment]
- Delete ARMv7, X86, and X64 targets and remove https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/binaries/android/jniLibs/(armeabi-v7a/x86/x86_64). You can also configure your gradle files to exclude these targets and use AArch64 only.

- Disable All extra features (VBSR, VMMR, LPCI, VCR...), you have to read the documentation

- Create your own assets folder and call it "models_lite" (for example). In "models_lite" copy only required models -> List of required (or optional models) is at 
https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/assets/models/README.md

"assets_lite" should only contain (to be double checked):

    + ultimateALPR-SDK_detecti_main.mobile.model.doubango
    + ultimateALPR-SDK_detecti_pysearch.mobile.model.doubango
    + charset_anpr_korean_size=78.txt
    + ultimateALPR-SDK_recogn1x100_latin.desktop.model.doubango

- Change your "build.gradle" to use "models_lite" instead of "models". The line to change is https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/f0a7d2a9783152f873264a5d18edfc974c015320/samples/android/sdk/build.gradle#L28

**The final apk size should be less than 15Mo**
