### ISSUE TITLE
AMD Ryzen 7 5700G + NVIDIA GeForce RTX 3050 FPS

### ISSUE THREAD

**Issue by Nook2007** [DoubangoTelecom/ultimateALPR-SDK#265]
Hi, we have same fps with enabled and disabled gpu. This is normal?
logs
without gpu https://gist.github.com/Nook2007/bf19cc75c9b9dc3263b36e404857f0e9
with gpu https://gist.github.com/Nook2007/c18d29313788b45c5eec3b2fb3acc0c9

and any updates on https://github.com/DoubangoTelecom/ultimateALPR-SDK/issues/155 ? we can't start using it

**Comment by DoubangoTelecom** [comment]
Hi,

From your logs you're using a new GPU and a new CUDA version 11.7 while using an old Tensorflow version (1.14). This won't work (GPU will  not be activated). Quote from https://github.com/DoubangoTelecom/ultimateALPR-SDK/blob/master/samples/c++/README.md#migration-to-tensorflow-2x-and-cuda-11x: "Our SDK is built and shipped with Tensorflow 1.x to make it work on oldest NVIDIA GPUs. If you want to use newest NVIDIA GPUs (e.g. RTX3060) which requires CUDA 11.x, then you'll need to upgrade the Tensorflow version. Check https://www.tensorflow.org/install/source#gpu to know which CUDA version is required for your Tensorflow version.". Follow the guide to update your Tensorflow version. If you still have issues, check the developer group's archive, there are plenty threads explaining how to fix this kind of issues. If you still don't have GPU acceleration, then open a new thread on the dev-group instead of using the issue tracker.
