### ISSUE TITLE
"7130 Segmentation fault" by using opencv and python

### ISSUE THREAD

**Issue by wesimet** [DoubangoTelecom/ultimateALPR-SDK#89]
Hi Doubango- Team

I use Raspi 4 and Python 3.8.  

When I start the following, everything works fine (python, read image with PIL):
sh file: 
PYTHONPATH=/home/pi/ultimateALPR-SDK/binaries/raspbian/armv7l:/home/pi/ultimate$
LD_LIBRARY_PATH=/home/pi/ultimateALPR-SDK/binaries/raspbian/armv7l:$LD_LIBRARY_$
python3.8 wesimet_pi.py --image /home/pi/image.jpg --assets /home/pi/ultimateALPR-$

python code:
image = Image.open(IMAGE)
width, height = image.size
format = ultimateAlprSdk.ULTALPR_SDK_IMAGE_TYPE_RGB24
checkResult("Process",
        ultimateAlprSdk.UltAlprSdkEngine_process(
            format,
            image.tobytes(), # type(x) == bytes
            width,
            height
            )
)

When I change the python code to opencv, an error occurs:
python code:
image2 = cv2.imread(IMAGE,-1)
height2, width2, channels = image2.shape
image2 = cv2.imencode('.jpg', image2)[1]
format = ultimateAlprSdk.ULTALPR_SDK_IMAGE_TYPE_RGB24
checkResult("Process",
        ultimateAlprSdk.UltAlprSdkEngine_process(
            format,
            image2.tobytes(), # type(x) == bytes
            width2,
            height2
            )
)

error:
[PythonRecognizer] Init: OK -> {}
run.sh: line 3:  7130 Segmentation fault      PYTHONPATH=/home/pi/ultimateALPR-SDK/binaries/raspbian/armv7l:/home/pi/ultimateALPR-SDK/python LD_LIBRARY_PATH=/home/pi/ultimateALPR-SDK/binaries/raspbian/armv7l:$LD_LIBRARY_PATH python3.8 wesimet_pi.py --image /home/pi/image.jpg --assets /home/pi/ultimateALPR-SDK/assets

How do i use python opencv?

**Comment by DoubangoTelecom** [comment]
This question is out of scope. The process function accepts raw data (uncompressed) and it's up to you to figure out how to convert OpenCV Mat to Python bytes. This said, you're encoding image2 (`cv2.imencode`) to jpg and passing it to process which is not correct. The image MUST NOT be encoded. You're getting segmentation fault because the encoded buffer is too short and we're trying to read up to (width2*height2*3) bytes. Another remark, images decoded by OpenCV are BGR24 not RGB24.

https://www.doubango.org/SDKs/anpr/docs/cpp-api.html#_CPPv4N15ultimateAlprSdk16UltAlprSdkEngine7processEK22ULTALPR_SDK_IMAGE_TYPEPKvK6size_tK6size_tK6size_tKi
